# Generated by Django 5.1.3 on 2024-11-26 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('image', models.URLField(null=True)),
                ('air_date', models.DateField(null=True)),
                ('overview', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'season',
                'verbose_name_plural': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('adult', models.BooleanField(default=False)),
                ('language', models.JSONField()),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('original_name', models.CharField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'series',
                'verbose_name_plural': 'seriess',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('vote_count', models.IntegerField(default=0)),
                ('adult', models.BooleanField(default=False)),
                ('language', models.JSONField()),
                ('poster_path', models.URLField(blank=True, null=True)),
                ('original_title', models.CharField(max_length=300, unique=True)),
                ('genre', models.ManyToManyField(to='movie.genre')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('overview', models.TextField(null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movie.season')),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.series'),
        ),
    ]
