# Generated by Django 5.1.3 on 2024-11-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_banner_series_banner_alter_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=2),
            preserve_default=False,
        ),
    ]
