# Generated by Django 5.1.3 on 2024-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_episode_rating_movie_rating_season_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='season',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='rating',
        ),
        migrations.AddField(
            model_name='episode',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='episode',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='series',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
