# Generated by Django 5.1.3 on 2024-11-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_episode_rating_remove_movie_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='casts',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='casts',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
