# Generated by Django 5.1.3 on 2024-11-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_casts_movie_director_series_casts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='episode',
            name='runtime',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.ManyToManyField(related_name='series_genres', to='movie.genre'),
        ),
    ]
