# Generated by Django 5.1.3 on 2024-11-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_episode_episode_number_episode_runtime_series_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='casts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='casts',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='director',
            field=models.JSONField(null=True),
        ),
    ]
