# Generated by Django 5.1.3 on 2024-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_casts_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
