# Generated by Django 5.1.3 on 2024-11-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_episode_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='runtime',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
