# Generated by Django 5.1.3 on 2024-11-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_episode_overview_alter_episode_runtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='casts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='director',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='episode',
            name='site',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movie',
            name='key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='site',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='season',
            name='casts',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='director',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='season',
            name='site',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='series',
            name='key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='series',
            name='site',
            field=models.CharField(default='', max_length=30),
        ),
    ]
