# Generated by Django 5.1.3 on 2024-11-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_episode_casts_episode_director_episode_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='key',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='site',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='key',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='site',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
