# Generated by Django 5.1.3 on 2024-12-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_alter_episode_key_alter_episode_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='key',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='site',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='key',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='site',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
