# Generated by Django 5.1.3 on 2024-12-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_alter_movie_key_alter_movie_site_alter_series_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='number_of_seasons',
            field=models.IntegerField(default=0),
        ),
    ]
