# Generated by Django 5.1.3 on 2024-12-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_series_number_of_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='json_episodes',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
