# Generated by Django 5.1.3 on 2024-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_season_json_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='json_episodes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
