# Generated by Django 5.1.3 on 2024-12-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_season_json_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_number',
            field=models.IntegerField(default=1),
        ),
    ]
