# Generated by Django 5.1.3 on 2024-11-26 02:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMovies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('episodes', models.ManyToManyField(blank=True, related_name='my_episodes', to='movie.episode')),
                ('movies', models.ManyToManyField(blank=True, related_name='my_movies', to='movie.movie')),
                ('series', models.ManyToManyField(blank=True, related_name='my_series', to='movie.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_saved_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
