import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

// import { SessionProvider } from "next-auth/react";

import { StoreProvider } from "./storeProvider";

import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const man_rope = Manrope({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <SessionProvider> */}
      <StoreProvider>
        <body className={`${man_rope.className} antialiased bg-[#141414]`}>
          <main className="w-11/12 mx-auto">{children}</main>
          <ToastContainer />
        </body>
      </StoreProvider>
      {/* </SessionProvider> */}
    </html>
  );
}
