# Generated by Django 5.1.3 on 2024-11-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_disliked_videos_user_liked_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
