# Generated by Django 5.1.3 on 2024-12-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
